### ISSUE TITLE
Question about lidar topic

### ISSUE THREAD

**Issue by youxiho1** [hatem-darweesh/op_bridge#2]
Hi, I'm also working on the ros2 bridge connecting autoware.universe and carla 0.9.13 recently (as you can see from my repos). 

By now, I'm stuck on the lidar topic reforwarding. It seems that if I don't deal with lidar topic perfectly, autoware's localization module also doesn't work (since the ndt_scan_matcher needs the lidar sensor output).

I find that you are publishing carla's lidar info to the topic /carla_pointcloud in your latest commit. But I didn't find a relevant remap in your op_bridge and op_agent repo. As far as I know, the lidar info needs to be published to /sensing/lidar/top/pointcloud_raw_ex. Then where did you do the remmaping (from /carla_pointcloud to /sensing/lidar/top/pointcloud_raw_ex )? Or am I missing something important?

I'm glad to hear from you. Thx

**Comment by hatem-darweesh** [comment]
@youxiho1 
I created a pointcloud interface node to the autoware.universe. It receives from the bridge and transform the cloud and publish the universe required topics. 

please use this repository. (openplanner) branch.
https://github.com/ZATiTech/autoware.universe.openplanner/tree/open-planner
and check the video tutorials 
https://youtu.be/EFH-vVxn180
https://youtu.be/dxwwNacez7o
